steps:
  - name: frontend
    image: node
    commands:
      - cd frontend
      - npm install
      - npm run build

  - name: backend
    image: docker-compose
    commands:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker-compose build
      - docker-compose up
