steps: 
  - name : frontend
    image: node
    commands: 
      - cd frontend
      - npm install
      - npm run build
      - npm start
  - name : backend
    image: docker-compose
    commands: 
      - docker-compose build
      - docker-compose up