version: "3.4"

services:
  emberjs:
    build:
      context: ./frontend/
      dockerfile: docker/Dockerfile
    ports:
      - 4200:4200
    volumes:
      - ./frontend:/frontend
      - /node_modules
