version: "3.4"

services:
  identifier:
    image: semtech/mu-identifier:1.9.1
    environment:
      SESSION_COOKIE_SECURE: 'on'
      DEFAULT_MU_AUTH_ALLOWED_GROUPS_HEADER: '[{"variables":[],"name":"public"}]'
    links:
      - dispatcher:dispatcher
    ports:
      - "80:80"

  search:
    image: semtech/mu-search:0.8.0
    links:
      - database:database
    volumes:
      - ./config/search:/config

  elasticsearch:
    image: semtech/mu-search-elastic-backend:1.0.0
    volumes:
      - ./data/elasticsearch/:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node

  dispatcher:
    image: semtech/mu-dispatcher:2.0.0
    links:
      - resource:resource
    volumes:
      - ./config/dispatcher:/config

  triplestore:
    image: redpencil/virtuoso:1.0.0
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/graphs/public"
    ports:
      - "8890:8890"
    volumes:
      - ./data/db:/data
      - ./config/virtuoso/virtuoso.ini:/data/virtuoso.ini

  resource:
    image: semtech/mu-cl-resources:1.20.0
    links:
      - database:database
    volumes:
      - ./config/resources:/config

  database:
    image: semtech/mu-authorization
    environment:
      MU_SPARQL_ENDPOINT: "http://triplestore:8890/sparql"
    volumes:
      - ./config/authorization:/config

  migrations:
    image: semtech/mu-migrations-service:0.4.0
    links:
      - triplestore:database
    volumes:
      - ./config/migrations:/data/migrations
