(in-package :mu-cl-resources)

(define-resource doctor ()
  :class (s-prefix "schema:Doctor")
  :properties `((:name :string ,(s-prefix "schema:name"))
                (:street :string ,(s-prefix "schema:street"))
                (:housenumber :integer ,(s-prefix "schema:integer"))
                (:postalcode :integer ,(s-prefix "schema:postalcode"))
                (:city :string ,(s-prefix "schema:city")))
  :has-one `((practice :via ,(s-prefix "schema:Practice")
                       :as "practice"))
  :resource-base (s-url "http://mu.semte.ch/application/doctors")
  :on-path "doctors")

(define-resource practice ()
  :class (s-prefix "schema:Practice")
  :properties `((:name :string ,(s-prefix "schema:practice"))
                (:street :string ,(s-prefix "schema:street"))
                (:housenumber :integer ,(s-prefix "schema:integer"))
                (:postalcode :integer ,(s-prefix "schema:postcode"))
                (:city :string ,(s-prefix "schema:gemeente"))
                (:type :string ,(s-prefix "schema:type")))
  :has-many `((doctor :via (s-prefix "schema:Practice")
                      :inverse t
                      :as "doctors"))
  :resource-base (s-url "http://mu.semte.ch/application/practices")
  :on-path "practices")
