(in-package :mu-cl-resources)

(define-resource doctor ()
  :class (s-prefix "schema:Doctor")
  :properties `((:naam :string ,(s-prefix "schema:naam"))
                (:straat :string ,(s-prefix "schema:straat"))
                (:huisnr :integer ,(s-prefix "schema:integer"))
                (:postcode :integer ,(s-prefix "schema:postcode"))
                (:gemeente :string ,(s-prefix "schema:gemeente"))
                (:praktijk :string, (s-prefix "schema:praktijk")))
              :has-one `((praktijk :via,(s-prefix "schema:praktijk")
              :as "praktijk"))`
  :resource-base (s-url "http://mu.semte.ch/application/doctor-app")
:on-path "doctors")

(define-resource praktijk ()
  :class (s-prefix "schema:Praktijk")
  :properties `((:praktijk :string ,(s-prefix "schema:praktijk"))
                (:straat :string ,(s-prefix "schema:straat"))
                (:huisnr :integer ,(s-prefix "schema:integer"))
                (:postcode :integer ,(s-prefix "schema:postcode"))
                (:gemeente :string ,(s-prefix "schema:gemeente"))
                (:type :string ,(s-prefix "schema:type")))
                :has-many `((doctor :via (s-prefix "schema:Praktijk")
                :inverse t
                :as "doctors"))
  :resource-base (s-url "http://mu.semte.ch/application/doctor-app")
:on-path "Praktijk")