(in-package :mu-cl-resources)

(define-resource doctor ()
  :class (s-prefix "schema:Doctor")
  :properties `((:naam :string ,(s-prefix "schema:naam"))
                (:straat :string ,(s-prefix "schema:straat"))
                (:huisnr :integer ,(s-prefix "schema:integer"))
                (:postcode :integer ,(s-prefix "schema:postcode"))
                (:gemeente :string ,(s-prefix "schema:gemeente"))
                (:type :string ,(s-prefix "schema:type")))
  :resource-base (s-url "http://mu.semte.ch/application/doctor-app")
:on-path "doctors")

;; (define-resource vestiging ()
;;   :class (s-prefix "schema:Vestiging")
;;   :properties `((:naam :string ,(s-prefix "schema:naam"))
;;                 (:straat :string ,(s-prefix "schema:straat"))
;;                 (:huisnr :integer ,(s-prefix "schema:integer"))
;;                 (:postcode :integer ,(s-prefix "schema:postcode"))
;;                 (:gemeente :string ,(s-prefix "schema:gemeente"))
;;                 (:type :string ,(s-prefix "schema:type")))
;;   :resource-base (s-url "http://mu.semte.ch/services/github/madnificent/book-service/authors/")
;; :on-path "vestiging")